// AI-generated face-constructor pieces (Higgsfield, pencil/ink sketch, unisex),
// background-removed to transparent PNGs and hosted on the app's Blob store.
// Placed on the Build canvas as image objects (move / resize / rotate). Start
// with 25 eyes across the emotional spectrum; noses, lips, brows, ears, lashes
// follow the same shape.

export interface FacePiece {
  id: string;
  label: string;
  url: string;
}

const HOST = "https://jz2zdu0bh6nu10tq.public.blob.vercel-storage.com/build-assets";
const EYE = (id: string) => `${HOST}/eyes-v2/${id}.png`;
// noses/lips/brows/ears/lashes each live in their own v1 folder.
const PART = (dir: string) => (id: string) => `${HOST}/${dir}/${id}.png`;
const NOSE = PART("noses-v2");
const LIP = PART("lips-v2");
const BROW = PART("brows-v1");
const EAR = PART("ears-v1");
const LASH = PART("lashes-v1");
const FACE = PART("faces-v2");
const HAIR = PART("hair-v1");

export const FACE_PIECE_GROUPS: { label: string; items: FacePiece[] }[] = [
  {
    // Base head shapes to drop first (lightly-guided outlines); build features
    // on top, then add a hairstyle from the Hair group.
    label: "Face shapes",
    items: [
      { id: "face_oval", label: "Oval", url: FACE("face_oval") },
      { id: "face_round", label: "Round", url: FACE("face_round") },
      { id: "face_square", label: "Square", url: FACE("face_square") },
      { id: "face_heart", label: "Heart", url: FACE("face_heart") },
      { id: "face_oblong", label: "Oblong", url: FACE("face_oblong") },
      { id: "face_diamond", label: "Diamond", url: FACE("face_diamond") },
      { id: "face_triangle", label: "Triangle", url: FACE("face_triangle") },
      { id: "face_inverted", label: "Inverted", url: FACE("face_inverted") },
      { id: "face_rectangle", label: "Rectangle", url: FACE("face_rectangle") },
      { id: "face_pear", label: "Pear", url: FACE("face_pear") },
      { id: "face_rounded_square", label: "Rounded square", url: FACE("face_rounded_square") },
      { id: "face_soft_oval", label: "Soft oval", url: FACE("face_soft_oval") },
      { id: "face_wide", label: "Wide", url: FACE("face_wide") },
      { id: "face_narrow", label: "Narrow", url: FACE("face_narrow") },
      { id: "face_egg", label: "Egg", url: FACE("face_egg") },
    ],
  },
  {
    label: "Eyes",
    items: [
      { id: "eye_calm", label: "Calm", url: EYE("eye_calm") },
      { id: "eye_content", label: "Content", url: EYE("eye_content") },
      { id: "eye_neutral", label: "Neutral", url: EYE("eye_neutral") },
      { id: "eye_joyful", label: "Joyful", url: EYE("eye_joyful") },
      { id: "eye_laughing", label: "Laughing", url: EYE("eye_laughing") },
      { id: "eye_loving", label: "Loving", url: EYE("eye_loving") },
      { id: "eye_hopeful", label: "Hopeful", url: EYE("eye_hopeful") },
      { id: "eye_proud", label: "Proud", url: EYE("eye_proud") },
      { id: "eye_playful", label: "Playful", url: EYE("eye_playful") },
      { id: "eye_determined", label: "Determined", url: EYE("eye_determined") },
      { id: "eye_surprised", label: "Surprised", url: EYE("eye_surprised") },
      { id: "eye_shocked", label: "Shocked", url: EYE("eye_shocked") },
      { id: "eye_confused", label: "Confused", url: EYE("eye_confused") },
      { id: "eye_skeptical", label: "Skeptical", url: EYE("eye_skeptical") },
      { id: "eye_anxious", label: "Anxious", url: EYE("eye_anxious") },
      { id: "eye_fearful", label: "Fearful", url: EYE("eye_fearful") },
      { id: "eye_sad", label: "Sad", url: EYE("eye_sad") },
      { id: "eye_crying", label: "Crying", url: EYE("eye_crying") },
      { id: "eye_annoyed", label: "Annoyed", url: EYE("eye_annoyed") },
      { id: "eye_angry", label: "Angry", url: EYE("eye_angry") },
      { id: "eye_furious", label: "Furious", url: EYE("eye_furious") },
      { id: "eye_disgusted", label: "Disgusted", url: EYE("eye_disgusted") },
      { id: "eye_bored", label: "Bored", url: EYE("eye_bored") },
      { id: "eye_sleepy", label: "Sleepy", url: EYE("eye_sleepy") },
      { id: "eye_exhausted", label: "Exhausted", url: EYE("eye_exhausted") },
    ],
  },
  {
    label: "Noses",
    items: [
      { id: "nose_button", label: "Button", url: NOSE("nose_button") },
      { id: "nose_broad", label: "Broad", url: NOSE("nose_broad") },
      { id: "nose_narrow", label: "Narrow", url: NOSE("nose_narrow") },
      { id: "nose_straight_side", label: "Straight (side)", url: NOSE("nose_straight_side") },
      { id: "nose_aquiline", label: "Aquiline", url: NOSE("nose_aquiline") },
      { id: "nose_upturned", label: "Upturned", url: NOSE("nose_upturned") },
      { id: "nose_long", label: "Long", url: NOSE("nose_long") },
      { id: "nose_bulbous", label: "Bulbous", url: NOSE("nose_bulbous") },
      { id: "nose_snub", label: "Snub", url: NOSE("nose_snub") },
      { id: "nose_pointed", label: "Pointed", url: NOSE("nose_pointed") },
      { id: "nose_roman", label: "Roman", url: NOSE("nose_roman") },
      { id: "nose_soft", label: "Soft", url: NOSE("nose_soft") },
      { id: "nose_wideflat", label: "Wide flat", url: NOSE("nose_wideflat") },
      { id: "nose_delicate", label: "Delicate", url: NOSE("nose_delicate") },
    ],
  },
  {
    label: "Lips",
    items: [
      { id: "lip_smile_soft", label: "Soft smile", url: LIP("lip_smile_soft") },
      { id: "lip_neutral", label: "Neutral", url: LIP("lip_neutral") },
      { id: "lip_laugh", label: "Laughing", url: LIP("lip_laugh") },
      { id: "lip_grin", label: "Grin", url: LIP("lip_grin") },
      { id: "lip_frown", label: "Frown", url: LIP("lip_frown") },
      { id: "lip_kiss", label: "Kiss", url: LIP("lip_kiss") },
      { id: "lip_thin", label: "Pressed thin", url: LIP("lip_thin") },
      { id: "lip_gasp", label: "Gasp", url: LIP("lip_gasp") },
      { id: "lip_smirk", label: "Smirk", url: LIP("lip_smirk") },
      { id: "lip_wail", label: "Wailing", url: LIP("lip_wail") },
      { id: "lip_gritted", label: "Gritted", url: LIP("lip_gritted") },
      { id: "lip_parted", label: "Parted", url: LIP("lip_parted") },
      { id: "lip_tongue", label: "Tongue out", url: LIP("lip_tongue") },
      { id: "lip_bite", label: "Biting lip", url: LIP("lip_bite") },
      { id: "lip_shout", label: "Shouting", url: LIP("lip_shout") },
      { id: "lip_content", label: "Content", url: LIP("lip_content") },
      { id: "lip_pout", label: "Pout", url: LIP("lip_pout") },
      { id: "lip_loving", label: "Loving", url: LIP("lip_loving") },
      { id: "lip_full", label: "Full", url: LIP("lip_full") },
      { id: "lip_wide_smile", label: "Beaming smile", url: LIP("lip_wide_smile") },
      { id: "lip_half_smile", label: "Half smile", url: LIP("lip_half_smile") },
      { id: "lip_o", label: "Round O", url: LIP("lip_o") },
      { id: "lip_whistle", label: "Whistle", url: LIP("lip_whistle") },
      { id: "lip_sneer", label: "Sneer", url: LIP("lip_sneer") },
      { id: "lip_disgust", label: "Disgust", url: LIP("lip_disgust") },
      { id: "lip_worried", label: "Worried", url: LIP("lip_worried") },
      { id: "lip_belly_laugh", label: "Belly laugh", url: LIP("lip_belly_laugh") },
      { id: "lip_yawn", label: "Yawn", url: LIP("lip_yawn") },
      { id: "lip_pressed_smile", label: "Pressed smile", url: LIP("lip_pressed_smile") },
      { id: "lip_downcast", label: "Downcast", url: LIP("lip_downcast") },
      { id: "lip_lick", label: "Licking", url: LIP("lip_lick") },
      { id: "lip_smug", label: "Smug", url: LIP("lip_smug") },
      { id: "lip_blow_kiss", label: "Blow kiss", url: LIP("lip_blow_kiss") },
      { id: "lip_grimace", label: "Grimace", url: LIP("lip_grimace") },
      { id: "lip_surprised_o", label: "Surprised", url: LIP("lip_surprised_o") },
      { id: "lip_relaxed_open", label: "Relaxed open", url: LIP("lip_relaxed_open") },
    ],
  },
  {
    label: "Brows",
    items: [
      { id: "brow_neutral", label: "Neutral", url: BROW("brow_neutral") },
      { id: "brow_raised", label: "Raised", url: BROW("brow_raised") },
      { id: "brow_angry", label: "Angry", url: BROW("brow_angry") },
      { id: "brow_furrowed", label: "Furrowed", url: BROW("brow_furrowed") },
      { id: "brow_worried", label: "Worried", url: BROW("brow_worried") },
      { id: "brow_flat", label: "Flat", url: BROW("brow_flat") },
      { id: "brow_bushy", label: "Bushy", url: BROW("brow_bushy") },
      { id: "brow_thin", label: "Thin", url: BROW("brow_thin") },
      { id: "brow_skeptical", label: "Skeptical", url: BROW("brow_skeptical") },
      { id: "brow_rounded", label: "Rounded", url: BROW("brow_rounded") },
      { id: "brow_angular", label: "Angular", url: BROW("brow_angular") },
      { id: "brow_heavy", label: "Heavy", url: BROW("brow_heavy") },
      { id: "brow_lifted", label: "Lifted", url: BROW("brow_lifted") },
      { id: "brow_bold", label: "Bold", url: BROW("brow_bold") },
      { id: "brow_calm", label: "Calm", url: BROW("brow_calm") },
    ],
  },
  {
    label: "Ears",
    items: [
      { id: "ear_average", label: "Average", url: EAR("ear_average") },
      { id: "ear_small", label: "Small", url: EAR("ear_small") },
      { id: "ear_large", label: "Large", url: EAR("ear_large") },
      { id: "ear_pointed", label: "Pointed", url: EAR("ear_pointed") },
      { id: "ear_rounded", label: "Rounded", url: EAR("ear_rounded") },
      { id: "ear_detailed", label: "Detailed", url: EAR("ear_detailed") },
      { id: "ear_side", label: "Side", url: EAR("ear_side") },
      { id: "ear_broad", label: "Broad", url: EAR("ear_broad") },
      { id: "ear_delicate", label: "Delicate", url: EAR("ear_delicate") },
      { id: "ear_lobe", label: "Full lobe", url: EAR("ear_lobe") },
    ],
  },
  {
    label: "Lashes",
    items: [
      { id: "lash_natural", label: "Natural", url: LASH("lash_natural") },
      { id: "lash_full", label: "Full", url: LASH("lash_full") },
      { id: "lash_dramatic", label: "Dramatic", url: LASH("lash_dramatic") },
      { id: "lash_wispy", label: "Wispy", url: LASH("lash_wispy") },
      { id: "lash_winged", label: "Winged", url: LASH("lash_winged") },
      { id: "lash_short", label: "Short", url: LASH("lash_short") },
      { id: "lash_clustered", label: "Clustered", url: LASH("lash_clustered") },
      { id: "lash_curled", label: "Curled", url: LASH("lash_curled") },
    ],
  },
  {
    // Wig-style hair — hair mass with an open face gap; drop over a face shape.
    label: "Hair",
    items: [
      { id: "hair_buzz", label: "Buzz", url: HAIR("hair_buzz") },
      { id: "hair_crew", label: "Crew", url: HAIR("hair_crew") },
      { id: "hair_fade", label: "Fade", url: HAIR("hair_fade") },
      { id: "hair_sidepart_m", label: "Side part", url: HAIR("hair_sidepart_m") },
      { id: "hair_slickback", label: "Slick-back", url: HAIR("hair_slickback") },
      { id: "hair_curly_short_m", label: "Short curly", url: HAIR("hair_curly_short_m") },
      { id: "hair_afro_m", label: "Afro (med)", url: HAIR("hair_afro_m") },
      { id: "hair_manbun", label: "Man bun", url: HAIR("hair_manbun") },
      { id: "hair_dreads", label: "Dreadlocks", url: HAIR("hair_dreads") },
      { id: "hair_receding", label: "Receding", url: HAIR("hair_receding") },
      { id: "hair_spiky", label: "Spiky", url: HAIR("hair_spiky") },
      { id: "hair_mohawk", label: "Mohawk", url: HAIR("hair_mohawk") },
      { id: "hair_pompadour", label: "Pompadour", url: HAIR("hair_pompadour") },
      { id: "hair_long_straight", label: "Long straight", url: HAIR("hair_long_straight") },
      { id: "hair_long_wavy", label: "Long wavy", url: HAIR("hair_long_wavy") },
      { id: "hair_bob", label: "Bob", url: HAIR("hair_bob") },
      { id: "hair_pixie", label: "Pixie", url: HAIR("hair_pixie") },
      { id: "hair_ponytail", label: "Ponytail", url: HAIR("hair_ponytail") },
      { id: "hair_bun", label: "Bun", url: HAIR("hair_bun") },
      { id: "hair_braids", label: "Box braids", url: HAIR("hair_braids") },
      { id: "hair_curly_long", label: "Long curly", url: HAIR("hair_curly_long") },
      { id: "hair_afro_f", label: "Afro (large)", url: HAIR("hair_afro_f") },
      { id: "hair_bangs", label: "Bangs", url: HAIR("hair_bangs") },
      { id: "hair_updo", label: "Updo", url: HAIR("hair_updo") },
      { id: "hair_pigtails", label: "Pigtails", url: HAIR("hair_pigtails") },
      { id: "hair_shoulder_layered", label: "Layered", url: HAIR("hair_shoulder_layered") },
      { id: "hair_high_top_fade", label: "High-top fade", url: HAIR("hair_high_top_fade") },
      { id: "hair_cornrows", label: "Cornrows", url: HAIR("hair_cornrows") },
      { id: "hair_waves_360", label: "360 waves", url: HAIR("hair_waves_360") },
      { id: "hair_twists", label: "Twists", url: HAIR("hair_twists") },
      { id: "hair_taper_curls", label: "Taper curls", url: HAIR("hair_taper_curls") },
      { id: "hair_undercut", label: "Undercut", url: HAIR("hair_undercut") },
      { id: "hair_quiff", label: "Quiff", url: HAIR("hair_quiff") },
      { id: "hair_caesar", label: "Caesar", url: HAIR("hair_caesar") },
      { id: "hair_afro_tall", label: "Tall afro", url: HAIR("hair_afro_tall") },
      { id: "hair_locs_long", label: "Long locs", url: HAIR("hair_locs_long") },
      { id: "hair_flat_top", label: "Flat top", url: HAIR("hair_flat_top") },
      { id: "hair_curtain", label: "Curtains", url: HAIR("hair_curtain") },
      { id: "hair_man_ponytail", label: "Man ponytail", url: HAIR("hair_man_ponytail") },
      { id: "hair_knotless", label: "Knotless braids", url: HAIR("hair_knotless") },
      { id: "hair_bantu", label: "Bantu knots", url: HAIR("hair_bantu") },
      { id: "hair_afro_puff", label: "Afro puff", url: HAIR("hair_afro_puff") },
      { id: "hair_curly_bob", label: "Curly bob", url: HAIR("hair_curly_bob") },
      { id: "hair_wavy_lob", label: "Wavy lob", url: HAIR("hair_wavy_lob") },
      { id: "hair_space_buns", label: "Space buns", url: HAIR("hair_space_buns") },
      { id: "hair_french_braid", label: "French braid", url: HAIR("hair_french_braid") },
      { id: "hair_half_up", label: "Half up", url: HAIR("hair_half_up") },
      { id: "hair_shag", label: "Shag + bangs", url: HAIR("hair_shag") },
      { id: "hair_twa", label: "TWA coily", url: HAIR("hair_twa") },
      { id: "hair_finger_waves", label: "Finger waves", url: HAIR("hair_finger_waves") },
      { id: "hair_side_braid", label: "Side braid", url: HAIR("hair_side_braid") },
      { id: "hair_sleek_pony", label: "Sleek ponytail", url: HAIR("hair_sleek_pony") },
    ],
  },
];
